-- Database: application_manager

-- DROP DATABASE application_manager;

CREATE DATABASE application_manager
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
	
	
-- Table: application

-- DROP TABLE application;

CREATE TABLE application
(
    app_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	app_key VARCHAR(50) NOT NULL,
    app_name VARCHAR(50) NOT NULL,
    app_uuid character(50) NOT NULL,
	creation_time TIMESTAMP  without time zone DEFAULT now()
)


-- INSERT DATA INTO TABLE application

INSERT INTO application(app_key, app_name, app_uuid)
VALUES ('9ddf09e0-bfa4-4204-b618-431184e7e051', 'app 1', 'df5e0cc2-01dd-44be-bef4-05eb836c5378');

INSERT INTO application(app_key, app_name, app_uuid)
VALUES ('adc828bd-8a1c-4924-8eee-1bf8cd0bdf10', 'app 2', '45bdb8c6-9df7-4afe-b45c-c151d87360d7');

INSERT INTO application(app_key, app_name, app_uuid)
VALUES ('ca54dfc0-c396-441f-b107-8d1719040d2d', 'app 3', '51305d56-395b-4951-9ced-a411cbd193c4');


-- SELECT FROM TABLE application

SELECT * FROM application


-- END SQL SCRIPTS 